openapi: 3.0.0
info:
  title: RED ANTISOCIAL PERSIDEV
  version: "1.0.0"
  description: API para la red antisocial de PERSIDEV
servers:
  url: "http://localhost:3001"
  description: Servidor local
components: 
  schemas:
    Comment:
      type: object
      properties:
        UserId:
          type: integer
          example: 1
          description: Id del usuario que creo el posteo.
        PostId:
          type: integer
          example: 1
          description: Id del posteo al que pertenece la imagen.
        content:
          type: string
          example: "Este es un comentario de prueba"
          description: Contenido del comentario.
        publicationDate:
          type: dateonly
          example: "2025-05-14"
          description: Fecha en que se realizo el comentario.

tags:
  - name: Comment
    description: Peticiones para realizar sobre comentarios

paths: 
  /comments:
    get:
      tags:
        - Comment
      summary: Obtener todos los comentarios.
      description: Obtener todos los comentarios.
      operationId: getComments
      responses:
        "200":
          description: Lista de comentarios.
        "204":
          description: No hay contenido.
        "404":
          description: No se encontraron comentarios.
        "500":
          description: Error interno del servidor.

    post:
      tags:
        - Comment
      summary: Crear un nuevo comentario.
      description: Crear un nuevo comentario.
      operationId: createComment
      requestBody:
        required: true
        description: crear un nuevo comentario.
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        "201":
          description: Comentario creado.
        "400":
          description: Solicitud incorrecta
        "500":
          description: Error interno del servidor

  /comments/{id}:
    get:
      tags:
        - Comment
      summary: Consultar un comentario por ID.
      description: Consultar un comentario por ID.
      operationId: getCommentById
      parameters:
        - name: id
          in: path
          description: ID del comentario a consultar
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Comentario devuelto.
        "204":
          description: No hay contenido.
        "404":
          description: No se encontro el comentario.
        "500":
          description: Error interno del servidor.    

    put:
      tags:
        - Comment
      summary: Actualizar un comentario por ID.
      description: Actualizar un comentario por ID.
      operationId: updateComment
      parameters:
        - name: id
          in: path
          description: ID del comentario a actualizar
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        "201":
          description: Comentario actualizado.
        "204":
          description: No hay contenido.
        "400":
          description: Solicitud incorrecta.
        "404":
          description: No se encontro el comentario.
        "500":
          description: Error interno del servidor.

    delete:
      tags:
        - Comment
      summary: Eliminar un comentario por ID.
      description: Eliminar un comentario por ID.
      operationId: deleteCommentById
      parameters:
        - name: id
          in: path
          description: ID del comentario a eliminar
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Comentario eliminado.
        "204":
          description: No hay contenido.
        "400":
          description: Solicitud incorrecta.
        "404":
          description: No se encontro el comentario.
        "500":
          description: Error interno del servidor.
